- name: test winrm connexion
  hosts: windows
  vars:
   command_result: ''
   ansible_user: Administrator
   ansible_password: Admin123
   ansible_connection: winrm
   ansible_winrm_server_cert_validation: ignore

  tasks:
   - win_shell: Get-Command

