- name: creating file foe scvmm connexion
  hosts: I-VMM-02.infra.bench
  vars:
    ansible_user: CFTest
    ansible_password: AntemetA2018
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
    ansible_winrm_transport: basic
    command_result: ''
  tasks:
    - name: creating the file
      win_template:
        dest: C:\Users\ansible_user\secretCredentials.txt
        src: secretCredential.j2
